import {
  Smartphone,
  Laptop,
  Headphones,
  Camera,
  Gamepad2,
  Keyboard,
  Truck,
  Headset,
  ShieldCheck,
  LayoutDashboard,
  Package,
  FileText,
  Grid,
  Users,
  LineChart,
  Settings,
} from "lucide-react";

export const Categories = [
  {
    title: "Phones",
    items: "128 items",
    description: "Flagship & Foldables",
    icon: Smartphone,
    badgeStyle: "bg-blue-950/80 border-blue-800/60 text-blue-400",
  },
  {
    title: "Laptops",
    items: "64 items",
    description: "Creator & Esports",
    icon: Laptop,
    badgeStyle: "bg-cyan-950/80 border-cyan-800/60 text-cyan-400",
  },
  {
    title: "Audio",
    items: "92 items",
    description: "Spatial & Planar",
    icon: Headphones,
    badgeStyle: "bg-indigo-950/80 border-indigo-800/60 text-indigo-400",
  },
  {
    title: "Cameras",
    items: "45 items",
    description: "8K Cinema & Logs",
    icon: Camera,
    badgeStyle: "bg-amber-950/80 border-amber-800/60 text-amber-500",
  },
  {
    title: "Gaming",
    items: "110 items",
    description: "Consoles & Decks",
    icon: Gamepad2,
    badgeStyle: "bg-rose-950/80 border-rose-800/60 text-rose-500",
  },
  {
    title: "Accessories",
    items: "230 items",
    description: "Keyboards & Docks",
    icon: Keyboard,
    badgeStyle: "bg-sky-950/80 border-sky-800/60 text-sky-400",
  },
];

export const MockProducts = [
  {
    id: 1,
    badge: "SALE -17%",
    badgeStyle: "bg-orange-950/80 text-orange-400 border-orange-800/50",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600",
    title: "Volt Pro Max 5G (Titanium...)",
    subtitle: "Snapdragon 8 Gen 3 · 120Hz LTPO OLED",
    rating: "4.9",
    reviews: "428",
    price: "₹74,999",
    originalPrice: "₹89,999",
  },
  {
    id: 2,
    badge: "BEST SELLER",
    badgeStyle: "bg-blue-950/80 text-blue-400 border-blue-800/50",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600",
    title: "Titan Pro X17 AI Neural Deck",
    subtitle: "RTX 4090 16GB · 64GB DDR5 · 240Hz QHD",
    rating: "5.0",
    reviews: "184",
    price: "₹2,49,999",
    originalPrice: "₹3,04,999",
  },
  {
    id: 3,
    badge: "HOT DEAL",
    badgeStyle: "bg-amber-950/80 text-amber-500 border-amber-800/50",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600",
    title: "Aura ANC Spatial Audio...",
    subtitle: "Planar Drivers · -45dB Active Noise...",
    rating: "4.8",
    reviews: "850",
    price: "₹19,999",
    originalPrice: "₹26,999",
  },
  {
    id: 4,
    badge: "NEW ARRIVAL",
    badgeStyle: "bg-cyan-950/80 text-cyan-400 border-cyan-800/50",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
    title: "Pulse Ultra ECG Titanium...",
    subtitle: "Sapphire Glass · Dual-Band GPS · 100m...",
    rating: "4.7",
    reviews: "890",
    price: "₹14,499",
    originalPrice: "₹18,999",
  },
];

export const Perks = [
  {
    title: "Free Shipping over ₹999",
    description: "Orders delivered via hyper-speed node",
    icon: Truck,
    badgeStyle: "bg-blue-950/80 border-blue-800/60 text-blue-400",
  },
  {
    title: "24/7 Expert Tech Support",
    description: "Direct engineer diagnostics on live call",
    icon: Headset,
    badgeStyle: "bg-cyan-950/80 border-cyan-800/60 text-cyan-400",
  },
  {
    title: "Easy 10-Day Returns",
    description: "Hassle-free instant refund & doorstep pickup",
    icon: ShieldCheck,
    badgeStyle: "bg-amber-950/80 border-amber-800/60 text-amber-500",
  },
];

export const MenuItems = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { id: "products", label: "Products", icon: Package },
  { id: "orders", label: "Orders", icon: FileText, badge: 18 },
  { id: "categories", label: "Categories", icon: Grid },
  { id: "customers", label: "Customers", icon: Users },
  { id: "analytics", label: "Analytics", icon: LineChart },
  { id: "settings", label: "System Settings", icon: Settings },
];
